/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnimatedLogo {
        "height"?: number;
        "imgUrl"?: string;
        "width"?: number;
    }
}
declare global {
    interface HTMLAnimatedLogoElement extends Components.AnimatedLogo, HTMLStencilElement {
    }
    var HTMLAnimatedLogoElement: {
        prototype: HTMLAnimatedLogoElement;
        new (): HTMLAnimatedLogoElement;
    };
    interface HTMLElementTagNameMap {
        "animated-logo": HTMLAnimatedLogoElement;
    }
}
declare namespace LocalJSX {
    interface AnimatedLogo {
        "height"?: number;
        "imgUrl"?: string;
        "width"?: number;
    }
    interface IntrinsicElements {
        "animated-logo": AnimatedLogo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "animated-logo": LocalJSX.AnimatedLogo & JSXBase.HTMLAttributes<HTMLAnimatedLogoElement>;
        }
    }
}
